import { marked } from "marked";
import { RunbookContent, SECTION_ORDER } from "./db";

export interface ExportMeta {
  runbookId: number;
  version: number;
  status: string;
  author: string;
  createdAt: string;
  approvedBy?: string;
}

export function toMarkdown(c: RunbookContent, meta: ExportMeta): string {
  const lines: string[] = [];
  lines.push(`# ${c.title}`);
  lines.push("");
  lines.push(
    `> **Severity:** ${c.severity.toUpperCase()} · **Version:** v${meta.version} · **Status:** ${meta.status} · **Generated:** ${meta.createdAt}`
  );
  if (c.tags.length) lines.push(`> **Tags:** ${c.tags.join(", ")}`);
  if (meta.approvedBy) lines.push(`> **Approved by:** ${meta.approvedBy}`);
  lines.push("");
  for (const s of SECTION_ORDER) {
    const body = c[s.key]?.trim();
    if (!body) continue;
    lines.push(`## ${s.label}`);
    lines.push("");
    lines.push(body);
    lines.push("");
  }
  lines.push("---");
  lines.push(
    `*Generated by [AutoRunbook](https://github.com/omrzk/autorunbook) — runbook #${meta.runbookId} v${meta.version}.*`
  );
  return lines.join("\n");
}

const HTML_STYLE = `
  :root { color-scheme: light; }
  * { box-sizing: border-box; }
  body { font-family: -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
         color: #1a2233; margin: 0; background: #f6f7f9; }
  .page { max-width: 820px; margin: 0 auto; padding: 48px 40px 64px; background: #fff;
          min-height: 100vh; }
  h1 { font-size: 28px; letter-spacing: -0.02em; margin: 0 0 8px; }
  h2 { font-size: 19px; letter-spacing: -0.01em; margin: 36px 0 12px; padding-bottom: 8px;
       border-bottom: 1px solid #e5e8ee; }
  h3 { font-size: 16px; margin: 24px 0 8px; }
  p, li { font-size: 14.5px; line-height: 1.65; }
  code { background: #f0f2f6; border: 1px solid #e2e6ee; border-radius: 4px;
         padding: 1px 5px; font-size: 13px; font-family: ui-monospace, "SF Mono", Menlo, monospace; }
  pre { background: #10141d; color: #dfe6f3; border-radius: 8px; padding: 14px 16px;
        overflow-x: auto; font-size: 13px; line-height: 1.55; }
  pre code { background: none; border: none; color: inherit; padding: 0; }
  blockquote { border-left: 3px solid #c8d0de; margin: 0; padding: 4px 16px; color: #48536a; }
  table { border-collapse: collapse; width: 100%; font-size: 14px; }
  th, td { border: 1px solid #e2e6ee; padding: 7px 10px; text-align: left; }
  th { background: #f4f6fa; }
  .meta { display: flex; flex-wrap: wrap; gap: 8px; margin: 14px 0 4px; }
  .badge { display: inline-block; font-size: 11.5px; font-weight: 600; letter-spacing: .04em;
           text-transform: uppercase; border-radius: 999px; padding: 4px 11px;
           background: #eef1f6; color: #47526b; }
  .badge.sev-critical { background: #fdebec; color: #b3261e; }
  .badge.sev-high { background: #fef0e6; color: #b25200; }
  .badge.sev-medium { background: #fff8e0; color: #8a6d00; }
  .badge.sev-low { background: #e9f7ee; color: #1d7a3e; }
  .badge.status-approved { background: #e9f7ee; color: #1d7a3e; }
  .badge.status-in_review { background: #fff8e0; color: #8a6d00; }
  footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #e5e8ee;
           font-size: 12px; color: #7c8699; }
  input[type=checkbox] { transform: translateY(1.5px); margin-right: 6px; }
  @media print { body { background: #fff; } .page { padding: 0; } }
`;

export function toHtml(c: RunbookContent, meta: ExportMeta): string {
  marked.setOptions({ gfm: true, breaks: false });
  const sections = SECTION_ORDER.map((s) => {
    const body = c[s.key]?.trim();
    if (!body) return "";
    return `<section><h2>${escapeHtml(s.label)}</h2>${marked.parse(body)}</section>`;
  }).join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(c.title)} — AutoRunbook</title>
<style>${HTML_STYLE}</style>
</head>
<body>
<div class="page">
  <h1>${escapeHtml(c.title)}</h1>
  <div class="meta">
    <span class="badge sev-${c.severity}">${c.severity}</span>
    <span class="badge status-${meta.status}">${meta.status.replace("_", " ")}</span>
    <span class="badge">v${meta.version}</span>
    ${c.tags.map((t) => `<span class="badge">${escapeHtml(t)}</span>`).join("")}
  </div>
  ${sections}
  <footer>Generated by AutoRunbook — runbook #${meta.runbookId} v${meta.version} · ${escapeHtml(meta.createdAt)}${meta.approvedBy ? ` · approved by ${escapeHtml(meta.approvedBy)}` : ""}</footer>
</div>
</body>
</html>`;
}

export function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
