import PDFDocument from "pdfkit";
import { RunbookContent, SECTION_ORDER } from "./db";
import type { ExportMeta } from "./export";

/**
 * Renders a runbook to PDF with a small purpose-built markdown layout engine
 * (headings, paragraphs, ordered/unordered lists, checkboxes, fenced code,
 * bold/inline-code). Uses PDFKit's built-in Helvetica/Courier so no font
 * files ship with the app.
 */

const M = 54; // page margin
const W = 612 - M * 2; // usable width (letter)

const SEV_COLORS: Record<string, string> = {
  critical: "#b3261e",
  high: "#b25200",
  medium: "#8a6d00",
  low: "#1d7a3e",
};

export function toPdf(c: RunbookContent, meta: ExportMeta): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "LETTER", margins: { top: M, bottom: M, left: M, right: M } });
    const bufs: Buffer[] = [];
    doc.on("data", (b: Buffer) => bufs.push(b));
    doc.on("end", () => resolve(Buffer.concat(bufs)));
    doc.on("error", reject);

    // ---- header ----
    doc.font("Helvetica-Bold").fontSize(21).fillColor("#1a2233").text(c.title, { width: W });
    doc.moveDown(0.4);
    doc
      .font("Helvetica")
      .fontSize(9.5)
      .fillColor(SEV_COLORS[c.severity] || "#47526b")
      .text(`SEVERITY: ${c.severity.toUpperCase()}`, { continued: true })
      .fillColor("#47526b")
      .text(
        `   ·   v${meta.version}   ·   ${meta.status.replace("_", " ")}   ·   ${meta.createdAt}` +
          (meta.approvedBy ? `   ·   approved by ${meta.approvedBy}` : "")
      );
    if (c.tags.length) {
      doc.fillColor("#7c8699").text(`tags: ${c.tags.join(", ")}`);
    }
    hr(doc);

    for (const s of SECTION_ORDER) {
      const body = c[s.key]?.trim();
      if (!body) continue;
      ensureSpace(doc, 60);
      doc.moveDown(0.9);
      doc.font("Helvetica-Bold").fontSize(14).fillColor("#1a2233").text(s.label, { width: W });
      doc.moveDown(0.3);
      renderMarkdown(doc, body);
    }

    doc.moveDown(1.2);
    hr(doc);
    doc
      .font("Helvetica")
      .fontSize(8.5)
      .fillColor("#9aa3b5")
      .text(`Generated by AutoRunbook — runbook #${meta.runbookId} v${meta.version}`);

    doc.end();
  });
}

function hr(doc: PDFKit.PDFDocument) {
  doc.moveDown(0.5);
  doc
    .moveTo(M, doc.y)
    .lineTo(M + W, doc.y)
    .lineWidth(0.7)
    .strokeColor("#dde2ea")
    .stroke();
  doc.moveDown(0.4);
}

function ensureSpace(doc: PDFKit.PDFDocument, needed: number) {
  if (doc.y + needed > 792 - M) doc.addPage();
}

function renderMarkdown(doc: PDFKit.PDFDocument, md: string) {
  const lines = md.replace(/\r\n/g, "\n").split("\n");
  let i = 0;
  let para: string[] = [];

  const flushPara = () => {
    if (!para.length) return;
    richText(doc, para.join(" "), { indent: 0 });
    doc.moveDown(0.45);
    para = [];
  };

  while (i < lines.length) {
    const line = lines[i];

    // fenced code block
    const fence = line.match(/^```(\w*)/);
    if (fence) {
      flushPara();
      const code: string[] = [];
      i++;
      while (i < lines.length && !lines[i].startsWith("```")) {
        code.push(lines[i]);
        i++;
      }
      i++; // closing fence
      codeBlock(doc, code.join("\n"));
      continue;
    }

    const h = line.match(/^(#{1,6})\s+(.*)/);
    if (h) {
      flushPara();
      ensureSpace(doc, 40);
      doc.moveDown(0.35);
      doc
        .font("Helvetica-Bold")
        .fontSize(h[1].length <= 3 ? 11.5 : 10.5)
        .fillColor("#2a3448")
        .text(stripInline(h[2]), { width: W });
      doc.moveDown(0.25);
      i++;
      continue;
    }

    const check = line.match(/^\s*[-*]\s+\[([ xX])\]\s+(.*)/);
    if (check) {
      flushPara();
      checkboxLine(doc, check[2], check[1] !== " ");
      i++;
      continue;
    }

    const ul = line.match(/^(\s*)[-*]\s+(.*)/);
    if (ul) {
      flushPara();
      bullet(doc, ul[2], Math.min(Math.floor(ul[1].length / 2), 2), "•");
      i++;
      continue;
    }

    const ol = line.match(/^(\s*)(\d+)[.)]\s+(.*)/);
    if (ol) {
      flushPara();
      bullet(doc, ol[3], Math.min(Math.floor(ol[1].length / 2), 2), `${ol[2]}.`);
      i++;
      continue;
    }

    const quote = line.match(/^>\s?(.*)/);
    if (quote) {
      flushPara();
      doc.font("Helvetica-Oblique").fontSize(10).fillColor("#48536a").text(stripInline(quote[1]), M + 14, doc.y, { width: W - 14 });
      doc.text("", M, doc.y); // reset x
      i++;
      continue;
    }

    if (line.trim() === "" || /^-{3,}$/.test(line.trim())) {
      flushPara();
      i++;
      continue;
    }

    para.push(line.trim());
    i++;
  }
  flushPara();
}

/** bold + inline-code aware text rendering */
function richText(
  doc: PDFKit.PDFDocument,
  text: string,
  opts: { indent: number }
) {
  ensureSpace(doc, 30);
  const segments = splitInline(text);
  const x = M + opts.indent;
  doc.fontSize(10.5).fillColor("#1f2940");
  segments.forEach((seg, idx) => {
    const last = idx === segments.length - 1;
    if (seg.code) doc.font("Courier").fontSize(9.5).fillColor("#3d4a66");
    else if (seg.bold) doc.font("Helvetica-Bold").fontSize(10.5).fillColor("#1f2940");
    else doc.font("Helvetica").fontSize(10.5).fillColor("#1f2940");
    if (idx === 0) {
      doc.text(seg.text, x, doc.y, { width: W - opts.indent, continued: !last, lineGap: 2.2 });
    } else {
      doc.text(seg.text, { continued: !last, lineGap: 2.2 });
    }
  });
  doc.text("", M, doc.y);
}

function bullet(doc: PDFKit.PDFDocument, text: string, depth: number, marker: string) {
  ensureSpace(doc, 26);
  const indent = 14 + depth * 14;
  doc.font("Helvetica").fontSize(10.5).fillColor("#1f2940");
  doc.text(marker, M + indent - 14, doc.y, { width: 14, continued: false });
  doc.moveUp();
  richTextAt(doc, text, M + indent + 4, W - indent - 4);
  doc.moveDown(0.18);
}

function checkboxLine(doc: PDFKit.PDFDocument, text: string, checked: boolean) {
  ensureSpace(doc, 26);
  const y = doc.y + 1.5;
  doc.rect(M + 2, y, 8.5, 8.5).lineWidth(0.9).strokeColor("#8b95a8").stroke();
  if (checked) {
    doc.font("Helvetica-Bold").fontSize(8).fillColor("#1d7a3e").text("✓", M + 3.5, y - 0.5, { lineBreak: false });
  }
  richTextAt(doc, text, M + 18, W - 18);
  doc.moveDown(0.18);
}

function richTextAt(doc: PDFKit.PDFDocument, text: string, x: number, width: number) {
  const segments = splitInline(text);
  segments.forEach((seg, idx) => {
    const last = idx === segments.length - 1;
    if (seg.code) doc.font("Courier").fontSize(9.5).fillColor("#3d4a66");
    else if (seg.bold) doc.font("Helvetica-Bold").fontSize(10.5).fillColor("#1f2940");
    else doc.font("Helvetica").fontSize(10.5).fillColor("#1f2940");
    if (idx === 0) doc.text(seg.text, x, doc.y, { width, continued: !last, lineGap: 2 });
    else doc.text(seg.text, { continued: !last, lineGap: 2 });
  });
  doc.text("", M, doc.y);
}

function codeBlock(doc: PDFKit.PDFDocument, code: string) {
  const lines = code.split("\n");
  const lineH = 11.5;
  const pad = 9;
  let remaining = [...lines];
  while (remaining.length) {
    const avail = 792 - M - doc.y - pad * 2 - 6;
    let take = Math.max(Math.floor(avail / lineH), 0);
    if (take < Math.min(3, remaining.length)) {
      doc.addPage();
      continue;
    }
    take = Math.min(take, remaining.length);
    const slice = remaining.slice(0, take);
    remaining = remaining.slice(take);
    const h = slice.length * lineH + pad * 2;
    doc.rect(M, doc.y, W, h).fillColor("#10141d").fill();
    doc.font("Courier").fontSize(8.8).fillColor("#dfe6f3");
    let y = doc.y + pad;
    for (const l of slice) {
      doc.text(l, M + pad, y, { width: W - pad * 2, lineBreak: false });
      y += lineH;
    }
    doc.y = y + pad;
    doc.x = M;
    doc.moveDown(0.3);
  }
}

interface InlineSeg {
  text: string;
  bold: boolean;
  code: boolean;
}

function splitInline(text: string): InlineSeg[] {
  const out: InlineSeg[] = [];
  const re = /(\*\*([^*]+)\*\*|`([^`]+)`)/g;
  let last = 0;
  let m: RegExpExecArray | null;
  while ((m = re.exec(text))) {
    if (m.index > last) out.push({ text: text.slice(last, m.index), bold: false, code: false });
    if (m[2] !== undefined) out.push({ text: m[2], bold: true, code: false });
    else out.push({ text: m[3], bold: false, code: true });
    last = m.index + m[0].length;
  }
  if (last < text.length) out.push({ text: text.slice(last), bold: false, code: false });
  return out.length ? out : [{ text, bold: false, code: false }];
}

function stripInline(text: string): string {
  return text.replace(/\*\*([^*]+)\*\*/g, "$1").replace(/`([^`]+)`/g, "$1");
}
